config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'

  resources :home, :only => [:index]
  resources :images, :except => [:edit]
  resources :posts
  resources :bios


end

app/models/bio.rb
class Bio < ActiveRecord::Base

  validates :name, :presence => true
  validates :content, :presence => true
  validates :url, :presence => true

end

app/models/image.rb
class Image < ActiveRecord::Base
  validates :url, :presence => true
end

app/models/post.rb
class Post <ActiveRecord::Base
  validates :title, :presence => true
  validates :author, :presence => true
  validates :content, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bios_controller.rb
class BiosController < ApplicationController

  def index
    @order_by = params[:Order]
    if @order_by == "Name"
      @bios = Bio.order(:name)
    elsif @order_by == "Updated Last"
      @bios = Bio.order(:updated_at)
    elsif @order_by == "Most Recent"
      @bios = Bio.order(:created_at)
    else
      @bios = Bio.all()
    end
  end

  def show
    @bio = Bio.find(params[:id])
  end

  def new
    @bio = Bio.new()
  end

  def create
    @bio = Bio.new(bio_params)
    if @bio.save
      redirect_to bios_path
    else
      render :new
    end
  end

  private
  def bio_params
    params.require(:bio).permit(:url, :name, :content)
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @bios = Bio.all()
    @bio = @bios.sample
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index
    @images = Image.all()
  end

  def new
    @image = Image.new()
  end

  def create
    @image = Image.new(image_params)
    if @image.save
      redirect_to images_path
    else
      render :new
    end
  end

  private
    def image_params
        params.require(:image).permit(:url, :caption)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @search_input = params[:search]
    if @search_input != nil
      @posts = Post.search(@search_input)
    else
      @posts = Post.all()
    end
  end

  def new
    @post = Post.new()
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :author, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bios/_form.html.erb
<%= render "layouts/errors", :object => @bio %>

<%= form_for @bio do |f| %>
<%= f.label "Image Url" %>
<%= f.text_field :url %>
<%= f.label "Name" %>
<%= f.text_field :name %>
<%= f.label "Bio" %>
<%= f.text_field :content %>
<%= f.submit :class => "btn btn-warning"%>
<% end %>

app/views/bios/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>Butlers!</h1>
    <%= link_to 'Add Butler', new_bio_path, :class => 'btn btn-xs btn-warning' %>
  </div>
</div>

<br />

<div class="row">
  <div class="col-sm-4">
    <h5>Order Results by:</h5>
    <%= form_tag("/bios", method: "get") do %>
    <%= select_tag "Order", options_for_select([["Name", "Name"], ["Updated At", "Updated At"], ["Most Resent", "Most Resent"]]), {:class=>'form-control', :onchange => "this.form.submit()"}  %>
    <br />
    <%= submit_tag ("Sort"), {:class => 'btn btn-warning'} %>
    <% end %>
  </div>
</div>

<% @bios.each do |bio| %>
  <div class="col-sm-6">
    <h3><img class="bio-pic" src='<%=bio.url%>' />
      <%=link_to bio.name, bio_path(bio) %>
    </h3>
  </div>
<% end %>

app/views/bios/new.html.erb
<%= render 'form' %>

app/views/bios/show.html.erb
<%= render 'layouts/profile' %>

app/views/home/index.html.erb
<h2>Butler trending right now!</h2>

<%= render 'layouts/profile' %>

app/views/images/_form.html.erb
<%= render "layouts/errors", :object => @image %>

<%= form_for @image do |f| %>
<%= f.label :url %>
<%= f.text_field :url %>
<%= f.label :caption %>
<%= f.text_field :caption %>
<%= f.submit :class => "btn-info"%>
<% end %>

app/views/images/index.html.erb
<h1>Pictures of the worlds greatest butlers</h1>
<%= link_to "Add Image", new_image_path %>
<br /><br />


<div class="row">
  <% @images.each do |image| %>
  <div class="col-sm-4">
    <img class="thumbnail" src="<%= image.url %>" />
    <em><%= image.caption %></em>
  </div>
  <% end %>
</div>

app/views/images/new.html.erb
<% content_for(:title, "New Image") %>

<h2>Enter the url of a picture of your favorite butler!</h2>

<%= render 'form' %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix the following errors:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/_profile.html.erb
<div class="col-sm-7">
  <div class="profile">
    <h1><%= @bio.name %></h1>
    <p><%=@bio.content %></p>
  </div>
</div>

<div class="col-sm-5">
  <img class="profile-pic"src="<%=@bio.url%>" />
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title)%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Great+Vibes' rel='stylesheet' type='text/css'>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Butler Lovin'", root_path, class: "navbar-brand"  %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav special-color">
          <li><%= link_to "Images", images_path %></li>
          <li><%= link_to "Forum", posts_path %></li>
          <li><%= link_to "Butler Bios", bios_path %></li>

        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <div class="container">

    <%= yield %>

  </div>

</body>
</html>

app/views/posts/_form.html.erb
<%= render "layouts/errors", :object => @post %>

<%= form_for @post do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :author %>
<%= f.text_field :author %>
<%= f.label :content %>
<%= f.text_field :content %>
<%= f.submit :class => "btn-info"%>
<% end %>

app/views/posts/index.html.erb
<h2>Forum</h2>

<%= form_tag("/posts", method: "get") do %>
  <%= text_field_tag "search" %>
  <%= submit_tag ("Search"), {:class => 'btn btn-warning'} %>
<% end %>

<%= link_to 'See All Posts', posts_path %>
<h3>Talk about your favorite man servant</h3>
<%= link_to "Add Post", new_post_path %>
<% @posts.each do |post| %>
  <div class="well">
    <p><%= post.title %></p>
    <p><%= post.author %></p>
    <p><%= post.content %></p>
  </div>
<% end %>